import { router } from "expo-router";
import { ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { BackLink } from "../components/BackLink";
import { BrandMark } from "../components/BrandMark";
import { CardContainer } from "../components/CardContainer";
import { PrimaryButton } from "../components/PrimaryButton";
import { SectionHeader } from "../components/SectionHeader";
import { StatusPill } from "../components/StatusPill";
import { getCurrentUser, logout } from "../services/api";
import type { ThemeColors } from "../theme/colors";
import { useThemeStyles } from "../theme/ThemeProvider";
import { initials } from "../components/AccountMenu";
export default function ProfileScreen() { const styles = useThemeStyles(createStyles); const user = getCurrentUser(); async function signOut() { await logout(); router.replace("/(auth)/login"); } if (!user) return <View style={styles.wrapper}><SafeAreaView><View style={styles.content}><BackLink /><BrandMark compact /><Text style={styles.title}>PLAYER{"\n"}<Text style={styles.primary}>PROFILE</Text></Text><Text style={styles.copy}>Sign in to view and manage your Pickelton profile.</Text><PrimaryButton icon="log-in-outline" label="LOG IN" onPress={() => router.replace("/(auth)/login")} /></View></SafeAreaView></View>; return <View style={styles.wrapper}><SafeAreaView><ScrollView contentContainerStyle={styles.content}><BackLink /><BrandMark compact /><Text style={styles.title}>PLAYER{"\n"}<Text style={styles.primary}>PROFILE</Text></Text><CardContainer style={styles.profile}><View style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>{initials(user.name)}</Text></View><View style={styles.identityCopy}><Text style={styles.name}>{user.name}</Text><Text style={styles.copy}>Pickelton player account</Text></View><StatusPill label="ACTIVE" /></View><Text style={styles.description}>Your personal home for club memberships, tournament activity, live courts, and host verification.</Text></CardContainer><SectionHeader title="PERSONAL DETAILS" /><CardContainer>{<Detail label="EMAIL ADDRESS" value={user.email} status={user.emailVerified} />}<Detail label="PHONE NUMBER" value={user.phoneNumber} status={user.phoneVerified} /><Detail label="DATE OF BIRTH" value={user.dateOfBirth} /></CardContainer><SectionHeader title="ACCOUNT SHORTCUTS" /><View style={styles.actions}><PrimaryButton icon="people-outline" label="MY CLUBS" onPress={() => router.push("/(tabs)/clubs")} style={styles.action} /><PrimaryButton icon="trophy-outline" label="TOURNAMENTS" onPress={() => router.push("/(tabs)/tournaments")} style={styles.action} /><PrimaryButton icon="shield-checkmark-outline" label="HOST DESK" onPress={() => router.push("/host/status")} style={styles.action} /></View><PrimaryButton icon="log-out-outline" label="LOG OUT" onPress={signOut} style={styles.logout} variant="outline" /></ScrollView></SafeAreaView></View>; }
function Detail({ label, value, status }: { label: string; value: string; status?: boolean }) { const styles = useThemeStyles(createStyles); return <View style={styles.detail}><View style={styles.detailCopy}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>{typeof status === "boolean" ? <StatusPill label={status ? "VERIFIED" : "PENDING"} tone={status ? "primary" : "gold"} /> : null}</View>; }
const createStyles = (colors: ThemeColors) => ({ wrapper: { backgroundColor: colors.background, flex: 1 }, content: { padding: 18, paddingBottom: 30 }, title: { color: colors.text, fontSize: 35, fontStyle: "italic", fontWeight: "900", lineHeight: 35, marginTop: 20 }, primary: { color: colors.primary }, copy: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 5 }, profile: { borderTopColor: colors.primary, borderTopWidth: 3, marginTop: 18 }, identity: { alignItems: "center", flexDirection: "row", gap: 10 }, avatar: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 27, height: 54, justifyContent: "center", width: 54 }, avatarText: { color: colors.primary, fontSize: 14, fontWeight: "900" }, identityCopy: { flex: 1 }, name: { color: colors.text, fontSize: 16, fontWeight: "900" }, description: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 16 }, detail: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", minHeight: 60 }, detailCopy: { flex: 1 }, detailLabel: { color: colors.muted, fontSize: 8, fontWeight: "900", letterSpacing: 0.6 }, detailValue: { color: colors.text, fontSize: 12, fontWeight: "800", marginTop: 5 }, actions: { gap: 9 }, action: { justifyContent: "flex-start" }, logout: { marginTop: 22 } });
