"use client";

import { Bell, CalendarClock, Check, CircleDollarSign, CreditCard, LoaderCircle,
  Mail, RefreshCw, Save, ShieldCheck, Smartphone, X } from "lucide-react";
import type { ReactNode } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getCurrentAccessToken } from "@/lib/supabase-access-token";
import PartnerSelect from "@/components/partner/PartnerSelect";
import "./page.css";

type Settings={notifications:{email:boolean|null;sms:boolean|null};booking:{autoConfirm:boolean|null;cancellationHours:number|null};payments:{currency:"INR"|null}};
const emptySettings:Settings={notifications:{email:null,sms:null},booking:{autoConfirm:null,cancellationHours:null},payments:{currency:null}};
const API_BASE=process.env.NEXT_PUBLIC_PARTNER_API_URL||"http://localhost:8090/api/v1";
async function settingsApi<T>(init?:RequestInit):Promise<T>{const token=await getCurrentAccessToken();let response:Response;
  try{response=await fetch(`${API_BASE}/settings`,{...init,headers:{Authorization:`Bearer ${token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}})}catch{throw new Error("Could not connect to the settings service. Check your connection and try again.")}
  const result=await response.json().catch(()=>null);if(!response.ok){const fallback=response.status===401?"Your session has expired. Please sign in again.":response.status===403?"You do not have permission to update these settings.":response.status===404?"Partner settings were not found.":response.status===400?"One or more settings are invalid.":"Unable to process the settings request.";throw new Error(result?.error?.message||fallback)}return result.data;}
function SettingsCard({id,icon,title,description,children}:{id?:string;icon:ReactNode;title:string;description:string;children:ReactNode}){return <section id={id} className="settings-card"><header className="settings-card-header"><span className="settings-card-icon">{icon}</span><div><h2>{title}</h2><p>{description}</p></div></header><div className="settings-card-body">{children}</div></section>}
function PreferenceRow({icon,title,description,children}:{icon:ReactNode;title:string;description:string;children:ReactNode}){return <div className="preference-row"><span className="preference-icon">{icon}</span><div className="preference-copy"><strong>{title}</strong><span>{description}</span></div><div className="preference-action">{children}</div></div>}
function Toggle({checked,onChange,label,configured}:{checked:boolean;onChange:(value:boolean)=>void;label:string;configured:boolean}){return <div className="setting-toggle-wrap">{!configured&&<small>Not configured</small>}<button type="button" className={`toggle-control ${checked?"is-active":""}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button></div>}
function Unsupported({title,description}:{title:string;description:string}){return <div className="empty-panel"><span className="empty-panel-icon"><ShieldCheck size={19}/></span><div><strong>{title}</strong><p>{description}</p></div></div>}

export default function SettingsPage(){const [settings,setSettings]=useState<Settings>(emptySettings);const [saved,setSaved]=useState<Settings>(emptySettings);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const value=await settingsApi<Settings>();setSettings(value);setSaved(value)}catch(err){setError(err instanceof Error?err.message:"Unable to load settings.")}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);const changed=useMemo(()=>JSON.stringify(settings)!==JSON.stringify(saved),[settings,saved]);
  function notification(key:"email"|"sms",value:boolean){setSettings(current=>({...current,notifications:{...current.notifications,[key]:value}}));setSuccess("")}
  function booking(key:"autoConfirm"|"cancellationHours",value:boolean|number|null){setSettings(current=>({...current,booking:{...current.booking,[key]:value}}));setSuccess("")}
  async function save(){if(!changed||saving)return;setSaving(true);setError("");setSuccess("");const payload:{notifications?:Record<string,boolean>;booking?:Record<string,boolean|number>;payments?:{currency:"INR"}}={};
    if(settings.notifications.email!==null||settings.notifications.sms!==null)payload.notifications={...(settings.notifications.email!==null?{email:settings.notifications.email}:{}),...(settings.notifications.sms!==null?{sms:settings.notifications.sms}:{})};
    if(settings.booking.autoConfirm!==null||settings.booking.cancellationHours!==null)payload.booking={...(settings.booking.autoConfirm!==null?{autoConfirm:settings.booking.autoConfirm}:{}),...(settings.booking.cancellationHours!==null?{cancellationHours:settings.booking.cancellationHours}:{})};
    if(settings.payments.currency)payload.payments={currency:settings.payments.currency};
    try{const updated=await settingsApi<Settings>({method:"PATCH",body:JSON.stringify(payload)});setSettings(updated);setSaved(updated);setSuccess("Settings saved successfully.")}catch(err){setError(err instanceof Error?err.message:"Unable to save settings.")}finally{setSaving(false)}}
  if(loading)return <div className="settings-page"><div className="settings-loading"><LoaderCircle size={28}/><strong>Loading your settings…</strong></div></div>;
  if(error&&!changed&&JSON.stringify(saved)===JSON.stringify(emptySettings))return <div className="settings-page"><section className="settings-card settings-error-state"><ShieldCheck size={28}/><h1>Could not load settings</h1><p>{error}</p><button type="button" className="primary-action" onClick={load}><RefreshCw size={16}/>Retry</button></section></div>;
  return <div className="settings-page"><div className="settings-page-header"><section className="settings-hero"><span className="hero-orbit hero-orbit-one"/><span className="hero-orbit hero-orbit-two"/><div className="settings-hero-copy"><span className="settings-eyebrow">PARTNER SETTINGS</span><h1>Business Settings</h1><p>Manage supported booking, notification and payment preferences.</p></div></section></div>
    {success&&<div className="settings-feedback success"><Check size={16}/><span>{success}</span><button type="button" onClick={()=>setSuccess("")} aria-label="Dismiss success"><X size={15}/></button></div>}{error&&<div className="settings-feedback error"><ShieldCheck size={16}/><span>{error}</span><button type="button" onClick={()=>setError("")} aria-label="Dismiss error"><X size={15}/></button></div>}
    <nav className="settings-nav" aria-label="Settings navigation"><a href="#notifications"><Bell size={16}/>Notifications</a><a href="#booking"><CalendarClock size={16}/>Bookings</a><a href="#payments"><CreditCard size={16}/>Payments</a><a href="#unsupported"><ShieldCheck size={16}/>Other Features</a></nav>
    <div className="settings-row"><SettingsCard id="notifications" icon={<Bell size={20}/>} title="Notifications" description="Notification channels stored for this partner."><div className="preference-list"><PreferenceRow icon={<Mail size={17}/>} title="Email Notifications" description="Receive partner account updates by email."><Toggle checked={settings.notifications.email??false} configured={settings.notifications.email!==null} onChange={value=>notification("email",value)} label="Email notifications"/></PreferenceRow><PreferenceRow icon={<Smartphone size={17}/>} title="SMS Notifications" description="Receive time-sensitive alerts by SMS."><Toggle checked={settings.notifications.sms??false} configured={settings.notifications.sms!==null} onChange={value=>notification("sms",value)} label="SMS notifications"/></PreferenceRow></div></SettingsCard>
      <SettingsCard id="booking" icon={<CalendarClock size={20}/>} title="Booking Preferences" description="Booking rules supported by the current settings model."><div className="preference-list"><PreferenceRow icon={<Check size={17}/>} title="Automatic Confirmation" description="Automatically confirm eligible bookings."><Toggle checked={settings.booking.autoConfirm??false} configured={settings.booking.autoConfirm!==null} onChange={value=>booking("autoConfirm",value)} label="Automatic confirmation"/></PreferenceRow></div><label className="form-field"><span>Cancellation Notice (hours)</span><input type="number" min="0" max="720" step="1" value={settings.booking.cancellationHours??""} placeholder="Not configured" onChange={event=>booking("cancellationHours",event.target.value===""?null:Number(event.target.value))}/><small>Allowed range: 0–720 hours.</small></label></SettingsCard></div>
    <div className="settings-row"><SettingsCard id="payments" icon={<CircleDollarSign size={20}/>} title="Payment Preferences" description="Currency stored in the partner settings."><label className="form-field"><span>Currency</span><PartnerSelect value={settings.payments.currency??""} onValueChange={value=>setSettings(current=>({...current,payments:{currency:value==="INR"?"INR":null}}))}><option value="">Not configured</option><option value="INR">INR — Indian Rupee</option></PartnerSelect></label><Unsupported title="Payment alerts and invoice emails unavailable" description="The current settings schema does not define these preferences."/></SettingsCard>
      <SettingsCard id="unsupported" icon={<ShieldCheck size={20}/>} title="Other Features" description="Features that require dedicated backend support."><Unsupported title="Security management unavailable" description="Password changes, two-factor authentication, sessions and login history are not represented by partner settings."/><Unsupported title="Venue defaults unavailable" description="Operating hours, holidays, pricing, booking windows, slot duration and buffers are not defined in the current settings model."/></SettingsCard></div>
    {changed&&<div className="settings-save-bar"><span>You have unsaved changes.</span><div><button type="button" className="discard-action" disabled={saving} onClick={()=>{setSettings(saved);setError("");setSuccess("")}}>Discard</button><button type="button" className="primary-action" disabled={saving} onClick={save}><Save size={17}/>{saving?"Saving…":"Save Changes"}</button></div></div>}
  </div>}
