"use client";

import Link from "next/link";
import { ArrowRight,Bell,CalendarCheck2,CalendarDays,IndianRupee,LayoutGrid,LoaderCircle,
  MapPin,Plus,RefreshCw,Settings2,TrendingDown,TrendingUp,Trophy,Users,Wrench } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useCallback,useEffect,useMemo,useState } from "react";
import { getCurrentAccessToken } from "@/lib/supabase-access-token";
import { formatPartnerDate, formatPartnerDateTime, formatPartnerTime, formatPartnerWeekday } from "@/lib/partner-date";
import "./page.css";

type Booking={id:string;reference:string;starts_at:string;ends_at:string;status:string;payment_status?:string;total_amount:number;court_name:string;customer_name:string};
type DashboardData={partner:{business_name:string;contact_name:string};metrics:{bookingsToday:number;bookingsYesterday:number;pendingBookings:number;revenueToday:number;revenueMonth:number;revenuePreviousMonth:number;averageBookingValue:number;totalCustomers:number;totalBookings:number;totalCourts:number;activeCourts:number;maintenanceCourts:number};
  revenueSeries:{date:string;revenue:number;bookings:number}[];bookingStatuses:{status:string;value:number}[];recentBookings:Booking[];todaysSchedule:Booking[];
  courtPerformance:{id:string;name:string;status:string;booking_count:number;revenue:number;booked_hours:number}[];peakBookingPeriod:{label:string;bookings:number}|null;
  capabilities:{occupancy:boolean;occupancyReason:string}};
const API_BASE=process.env.NEXT_PUBLIC_PARTNER_API_URL||"http://localhost:8090/api/v1";
const quickActions=[{title:"New Booking",description:"Create a court reservation",href:"/partner/bookings/add",icon:CalendarCheck2},{title:"Add Court",description:"Register a new court",href:"/partner/courts/add",icon:Plus},{title:"View Schedule",description:"Review today’s bookings",href:"/partner/bookings",icon:CalendarDays},{title:"Manage Availability",description:"Update court availability",href:"/partner/courts",icon:Settings2}];
function money(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value)}
function initials(name:string){return name.split(" ").filter(Boolean).map(p=>p[0]).join("").slice(0,2).toUpperCase()}
function tone(status:string){return status==="REJECTED"?"cancelled":status.toLowerCase()}
function percent(value:number,total:number){return total?value/total*100:0}
function growth(current:number,previous:number){if(previous===0)return current===0?0:null;return (current-previous)/previous*100}
async function loadDashboard(signal?:AbortSignal){const token=await getCurrentAccessToken();let response:Response;try{response=await fetch(`${API_BASE}/dashboard`,{signal,headers:{Authorization:`Bearer ${token}`}})}catch(error){if((error as Error).name==="AbortError")throw error;throw new Error("Could not connect to the dashboard service.")}
  const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error?.message||(response.status===401?"Your session has expired. Please sign in again.":"Unable to load dashboard."));return result.data as DashboardData;}
function Empty({children}:{children:string}){return <div className="dashboard-empty-state">{children}</div>}

export default function DashboardPage(){const [data,setData]=useState<DashboardData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{setData(await loadDashboard(signal))}catch(err){if((err as Error).name!=="AbortError")setError(err instanceof Error?err.message:"Unable to load dashboard.")}finally{if(!signal?.aborted)setLoading(false)}},[]);
  useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort()},[load]);
  const derived=useMemo(()=>{if(!data)return null;const monthlyGrowth=growth(data.metrics.revenueMonth,data.metrics.revenuePreviousMonth);const bookingGrowth=growth(data.metrics.bookingsToday,data.metrics.bookingsYesterday);
    const maxRevenue=Math.max(1,...data.revenueSeries.map(item=>item.revenue));const statusTotal=data.bookingStatuses.reduce((sum,item)=>sum+item.value,0);const bestCourt=data.courtPerformance.find(court=>court.revenue>0)??null;
    const alerts=[...(data.metrics.pendingBookings?[{title:"Booking approval required",description:`${data.metrics.pendingBookings} booking${data.metrics.pendingBookings===1?" is":"s are"} waiting for confirmation.`,icon:CalendarCheck2,tone:"attention"}]:[]),...(data.metrics.maintenanceCourts?[{title:"Court maintenance",description:`${data.metrics.maintenanceCourts} court${data.metrics.maintenanceCourts===1?" is":"s are"} currently in maintenance.`,icon:Wrench,tone:"attention"}]:[])];
    return {monthlyGrowth,bookingGrowth,maxRevenue,statusTotal,bestCourt,alerts}},[data]);
  if(loading&&!data)return <main className="dashboard-page"><div className="dashboard-loading"><LoaderCircle size={30}/><strong>Loading your dashboard…</strong></div></main>;
  if(!data||!derived)return <main className="dashboard-page"><section className="dashboard-card dashboard-error-state"><h1>Could not load dashboard</h1><p>{error}</p><button type="button" className="dashboard-primary-action" onClick={()=>load()}><RefreshCw size={16}/>Retry</button></section></main>;
  const {metrics}=data;const kpis:[string,string,string,string,LucideIcon][]=[["Today’s Bookings",String(metrics.bookingsToday),derived.bookingGrowth===null?"New activity":`${derived.bookingGrowth>=0?"+":""}${derived.bookingGrowth.toFixed(1)}% from yesterday`,"",CalendarCheck2],["Today’s Revenue",money(metrics.revenueToday),"Confirmed and completed bookings","",IndianRupee],["Customers",String(metrics.totalCustomers),"Customers with bookings","",Users],["Active Courts",String(metrics.activeCourts),`${metrics.totalCourts} total courts`,"",LayoutGrid]];
  return <main className="dashboard-page">
    <section className="dashboard-hero"><span className="dashboard-hero-orbit dashboard-hero-orbit-large"/><span className="dashboard-hero-orbit dashboard-hero-orbit-small"/><div className="dashboard-hero-main"><div className="dashboard-hero-copy"><span className="dashboard-eyebrow">TODAY&apos;S OVERVIEW</span><h1>Welcome, {data.partner.contact_name}!</h1><p>Here&apos;s everything happening across {data.partner.business_name} today.</p></div></div><div className="dashboard-hero-kpis"><div className="dashboard-hero-kpi"><span>Today’s Bookings</span><strong>{metrics.bookingsToday}</strong></div><div className="dashboard-hero-kpi"><span>Active Courts</span><strong>{metrics.activeCourts}</strong></div><div className="dashboard-hero-kpi"><span>Revenue</span><strong>{money(metrics.revenueToday)}</strong></div></div></section>
    {error&&<div className="dashboard-inline-error">{error}<button type="button" onClick={()=>load()}><RefreshCw size={14}/>Retry</button></div>}
    <section className="dashboard-quick-actions"><header className="dashboard-section-heading"><div><span className="dashboard-section-label">SHORTCUTS</span><h2>Quick Actions</h2></div></header><div className="dashboard-quick-action-grid">{quickActions.map(action=>{const Icon=action.icon;return <Link className="dashboard-quick-action" href={action.href} key={action.title}><span className="dashboard-quick-action-icon"><Icon size={19}/></span><span className="dashboard-quick-action-copy"><strong>{action.title}</strong><small>{action.description}</small></span><ArrowRight className="dashboard-quick-action-arrow" size={17}/></Link>})}</div></section>
    <section className="dashboard-stats-grid" aria-label="Dashboard statistics">{kpis.map(([label,value,detail,detailClass,Icon])=><article className="dashboard-stat-card" key={label}><div className="dashboard-stat-header"><span>{label}</span><span className="dashboard-stat-icon"><Icon size={19}/></span></div><strong className="dashboard-stat-value">{value}</strong><p className={`dashboard-stat-detail ${detailClass}`}>{detail}</p></article>)}</section>
    <section className="dashboard-primary-grid"><article className="dashboard-card dashboard-revenue-card"><header className="dashboard-card-header"><div><span className="dashboard-section-label">ANALYTICS</span><h2>Revenue Overview</h2><p>Real revenue for the last seven days.</p></div><span className="dashboard-period">Last 7 Days</span></header><div className="dashboard-revenue-metrics"><div><span>This Month</span><strong>{money(metrics.revenueMonth)}</strong></div><div><span>Average Booking Value</span><strong>{money(metrics.averageBookingValue)}</strong></div><div><span>Monthly Growth</span><strong className={derived.monthlyGrowth!==null&&derived.monthlyGrowth<0?"dashboard-negative-text":"dashboard-positive-text"}>{derived.monthlyGrowth===null?"New":`${derived.monthlyGrowth>=0?"+":""}${derived.monthlyGrowth.toFixed(1)}%`}</strong></div></div><div className="dashboard-revenue-chart" role="img" aria-label="Revenue for the last seven days"><div className="dashboard-chart-grid"><span/><span/><span/><span/></div>{data.revenueSeries.map(item=><div className="dashboard-chart-column" key={item.date}><div className="dashboard-chart-track"><span className="dashboard-chart-bar" style={{height:`${Math.max(item.revenue?5:0,item.revenue/derived.maxRevenue*100)}%`}} title={`${formatPartnerDate(item.date)}: ${money(item.revenue)}`}/></div><span>{formatPartnerWeekday(item.date)}</span></div>)}</div></article>
      <article className="dashboard-card dashboard-status-card"><header className="dashboard-card-header"><div><span className="dashboard-section-label">TODAY</span><h2>Booking Status</h2><p>Current distribution across {metrics.bookingsToday} bookings.</p></div></header>{derived.statusTotal?<><div className="dashboard-status-bar">{data.bookingStatuses.map(item=><span className={tone(item.status)} style={{width:`${percent(item.value,derived.statusTotal)}%`}} key={item.status}/>)}</div><div className="dashboard-status-list">{data.bookingStatuses.map(item=><div className="dashboard-status-row" key={item.status}><span className={`dashboard-status-dot ${tone(item.status)}`}/><span>{item.status}</span><strong>{item.value}</strong></div>)}</div></>:<Empty>No bookings today.</Empty>}</article></section>
    <section className="dashboard-secondary-grid"><article className="dashboard-card"><header className="dashboard-card-header"><div><span className="dashboard-section-label">BUSINESS HEALTH</span><h2>Business Insights</h2><p>Indicators calculated from current activity.</p></div></header><div className="dashboard-insights-grid"><Insight icon={CalendarCheck2} label="Peak Booking Period" value={data.peakBookingPeriod?.label??"Not enough data"} detail={data.peakBookingPeriod?`${data.peakBookingPeriod.bookings} bookings this month`:"No bookings this month"}/><Insight icon={Trophy} label="Best Performing Court" value={derived.bestCourt?.name??"Not enough data"} detail={derived.bestCourt?`${money(derived.bestCourt.revenue)} this month`:"No qualifying revenue"} tone="positive"/><Insight icon={CalendarDays} label="Pending Bookings" value={String(metrics.pendingBookings)} detail="Currently awaiting confirmation" tone={metrics.pendingBookings?"attention":""}/><Insight icon={derived.monthlyGrowth!==null&&derived.monthlyGrowth<0?TrendingDown:TrendingUp} label="Monthly Growth" value={derived.monthlyGrowth===null?"New":`${derived.monthlyGrowth.toFixed(1)}%`} detail="Compared with previous month" tone={derived.monthlyGrowth!==null&&derived.monthlyGrowth<0?"attention":"positive"}/></div></article>
      <article className="dashboard-card"><header className="dashboard-card-header"><div><span className="dashboard-section-label">OPERATIONS</span><h2>Today’s Schedule</h2><p>Actual court activity for today.</p></div><Link href="/partner/bookings" className="dashboard-text-action">Full schedule<ArrowRight size={15}/></Link></header>{data.todaysSchedule.length?<div className="dashboard-schedule-list">{data.todaysSchedule.map((booking,index)=><div className={`dashboard-schedule-item ${index===0?"is-next":""}`} key={booking.id}><time>{formatPartnerTime(booking.starts_at)}</time><span className="dashboard-avatar">{initials(booking.customer_name)}</span><div className="dashboard-schedule-copy"><strong>{booking.customer_name}</strong><span><MapPin size={12}/>{booking.court_name}</span></div><span className={`dashboard-status-chip ${tone(booking.status)}`}>{booking.status}</span></div>)}</div>:<Empty>No bookings scheduled today.</Empty>}</article></section>
    <section className="dashboard-lower-grid"><article className="dashboard-card dashboard-bookings-card"><header className="dashboard-card-header"><div><span className="dashboard-section-label">ACTIVITY</span><h2>Recent Bookings</h2><p>Latest partner reservations.</p></div><Link href="/partner/bookings" className="dashboard-outline-action">View All<ArrowRight size={15}/></Link></header>{data.recentBookings.length?<div className="dashboard-table-wrapper"><table className="dashboard-booking-table"><thead><tr><th>Booking ID</th><th>Customer</th><th>Court</th><th>Date & Time</th><th>Amount</th><th>Status</th><th className="dashboard-action-heading">Action</th></tr></thead><tbody>{data.recentBookings.map(booking=><tr key={booking.id}><td><span className="dashboard-booking-id">{booking.reference}</span></td><td><div className="dashboard-customer-cell"><span className="dashboard-avatar">{initials(booking.customer_name)}</span><strong>{booking.customer_name}</strong></div></td><td>{booking.court_name}</td><td>{formatPartnerDateTime(booking.starts_at)}</td><td>{money(Number(booking.total_amount))}</td><td><span className={`dashboard-status-chip ${tone(booking.status)}`}>{booking.status}</span></td><td className="dashboard-action-cell"><Link href={`/partner/bookings/${booking.id}`} className="dashboard-table-action">View</Link></td></tr>)}</tbody></table></div>:<Empty>No bookings have been created yet.</Empty>}</article>
      <article className="dashboard-card"><header className="dashboard-card-header"><div><span className="dashboard-section-label">COURTS</span><h2>Court Performance</h2><p>Booked hours and revenue this month.</p></div></header>{data.courtPerformance.length?<div className="dashboard-court-list">{data.courtPerformance.map(court=><div className="dashboard-court-item" key={court.id}><div className="dashboard-court-heading"><div><strong>{court.name}</strong><span>{money(court.revenue)} revenue</span></div><span className={`dashboard-availability ${court.status==="ACTIVE"?"available":"busy"}`}>{court.status}</span></div><div className="dashboard-court-progress-heading"><span>Revenue contribution</span><div><strong>{percent(court.revenue,metrics.revenueMonth).toFixed(0)}%</strong><span className="dashboard-trend positive">{court.booked_hours.toFixed(1)} hrs</span></div></div><div className="dashboard-progress" role="progressbar" aria-label={`${court.name} revenue contribution`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent(court.revenue,metrics.revenueMonth)}><span style={{width:`${percent(court.revenue,metrics.revenueMonth)}%`}}/></div></div>)}</div>:<Empty>No courts have been added yet.</Empty>}<p className="dashboard-metric-note">Occupancy unavailable: {data.capabilities.occupancyReason}</p></article></section>
    <section className="dashboard-card dashboard-notifications-card"><header className="dashboard-card-header"><div><span className="dashboard-section-label">UPDATES</span><h2>Operational Alerts</h2><p>Current alerts derived from real partner data.</p></div><Bell size={18}/></header>{derived.alerts.length?<div className="dashboard-notification-grid">{derived.alerts.map(alert=>{const Icon=alert.icon;return <article className="dashboard-notification" key={alert.title}><span className={`dashboard-notification-icon ${alert.tone}`}><Icon size={18}/></span><div><strong>{alert.title}</strong><p>{alert.description}</p><time>Current</time></div></article>})}</div>:<Empty>No operational alerts right now.</Empty>}</section>
  </main>}

function Insight({icon:Icon,label,value,detail,tone=""}:{icon:LucideIcon;label:string;value:string;detail:string;tone?:string}){return <div className="dashboard-insight"><span className={`dashboard-insight-icon ${tone}`}><Icon size={18}/></span><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>}
