import { useEffect, useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { AppHeader } from "../../components/AppHeader";
import { CardContainer } from "../../components/CardContainer";
import { EmptyState } from "../../components/EmptyState";
import { InputField } from "../../components/InputField";
import { PrimaryButton } from "../../components/PrimaryButton";
import { ScreenIntro } from "../../components/ScreenIntro";
import { SectionHeader } from "../../components/SectionHeader";
import { StatusPill } from "../../components/StatusPill";
import { apiErrorMessage, createCommunityPost, deleteCommunityPost, fetchCommunityPosts, getCurrentUser, type CommunityPost } from "../../services/api";
import type { ThemeColors } from "../../theme/colors";
import { useThemeStyles } from "../../theme/ThemeProvider";
export default function CommunityScreen() {
  const styles = useThemeStyles(createStyles);
  const [posts, setPosts] = useState<CommunityPost[]>([]); const [page, setPage] = useState(0); const [last, setLast] = useState(true); const [liked, setLiked] = useState<string[]>([]); const [form, setForm] = useState({ tag: "MATCHDAY", content: "" }); const [error, setError] = useState(""); const currentId = getCurrentUser()?.userId ?? getCurrentUser()?.id;
  useEffect(() => { load(0, true); }, []);
  async function load(next: number, replace = false) { try { const result = await fetchCommunityPosts(next); setPosts((current) => replace ? result.content : [...current, ...result.content]); setPage(result.page); setLast(result.last); setError(""); } catch (cause) { setError(apiErrorMessage(cause)); if (replace) setPosts([]); } }
  async function submit() { if (!form.content.trim()) return; try { const post = await createCommunityPost(form); setPosts((current) => [post, ...current]); setForm({ tag: "MATCHDAY", content: "" }); } catch (cause) { setError(apiErrorMessage(cause)); } }
  async function remove(id: string) { try { await deleteCommunityPost(id); setPosts((current) => current.filter((post) => post.id !== id)); } catch (cause) { setError(apiErrorMessage(cause)); } }
  return <View style={styles.wrapper}><SafeAreaView edges={["top", "bottom"]} style={styles.safe}><ScrollView contentContainerStyle={styles.content}><AppHeader eyebrow="COMMUNITY NETWORK" title="Player activity" /><ScreenIntro title="THE LOCAL" accent="RALLY FEED" copy="Sessions, wins, club notes, and the occasional post-match truth from players around Bengaluru." /><CardContainer style={styles.composer}><InputField label="POST TAG" value={form.tag} onChangeText={(tag) => setForm((current) => ({ ...current, tag }))} /><InputField label="SHARE WITH THE COMMUNITY" multiline placeholder="What is happening on court?" value={form.content} onChangeText={(content) => setForm((current) => ({ ...current, content }))} /><PrimaryButton icon="send-outline" label="PUBLISH POST" onPress={submit} /></CardContainer><SectionHeader title="LATEST POSTS" action={last ? "LIVE FEED" : `PAGE ${page + 1}`} />{error ? <Text style={styles.note}>{error}</Text> : null}{posts.length ? posts.map((post) => { const isLiked = liked.includes(post.id); return <CardContainer key={post.id} style={styles.post}><View style={styles.top}><View style={styles.avatar}><Text style={styles.avatarText}>{initials(post.authorName)}</Text></View><View style={styles.identity}><Text style={styles.name}>{post.authorName}</Text><Text style={styles.meta}>{time(post.createdAt)}</Text></View><StatusPill label={post.tag} tone="gold" /></View><Text style={styles.copy}>{post.content}</Text><View style={styles.actions}><Pressable onPress={() => setLiked((current) => isLiked ? current.filter((id) => id !== post.id) : [...current, post.id])}><Text style={isLiked ? styles.active : styles.action}>{isLiked ? "LIKED" : "LIKE"}</Text></Pressable>{post.authorId === currentId ? <Pressable onPress={() => remove(post.id)}><Text style={styles.delete}>DELETE</Text></Pressable> : null}</View></CardContainer>; }) : <EmptyState title="THE FEED IS QUIET" copy="Publish the first community note and start the conversation." />}{!last ? <PrimaryButton label="LOAD MORE POSTS" variant="outline" onPress={() => load(page + 1)} /> : null}</ScrollView></SafeAreaView></View>;
}
function initials(name: string) { return name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); } function time(value: string) { return new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short" }).toUpperCase(); }
const createStyles = (colors: ThemeColors) => ({ wrapper: { backgroundColor: colors.background, flex: 1 }, safe: { flex: 1 }, content: { padding: 18, paddingBottom: 28 }, composer: { borderTopColor: colors.primary, borderTopWidth: 3, marginTop: 20, paddingBottom: 14 }, post: { borderTopColor: colors.primary, borderTopWidth: 2, gap: 13, marginBottom: 10 }, top: { alignItems: "center", flexDirection: "row", gap: 10 }, avatar: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: 18, height: 36, justifyContent: "center", width: 36 }, avatarText: { color: colors.primary, fontSize: 9, fontWeight: "900" }, identity: { flex: 1 }, name: { color: colors.text, fontSize: 12, fontWeight: "900" }, meta: { color: colors.muted, fontSize: 8, fontWeight: "900", marginTop: 4 }, copy: { color: colors.text, fontSize: 12, lineHeight: 18 }, actions: { borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: 20, paddingTop: 11 }, action: { color: colors.muted, fontSize: 9, fontWeight: "900" }, active: { color: colors.primary, fontSize: 9, fontWeight: "900" }, delete: { color: colors.danger, fontSize: 9, fontWeight: "900" }, note: { color: colors.gold, fontSize: 10, lineHeight: 15, marginBottom: 10 } });
