"use client";

import {
  ArrowDown, ArrowUp, BarChart3, CalendarDays, CheckCircle2, ChevronLeft,
  ChevronRight, Clock3, Download, FileSpreadsheet, FileText, IndianRupee,
  RefreshCw, TrendingDown, TrendingUp, Users, X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getCurrentAccessToken } from "@/lib/supabase-access-token";
import PartnerDatePicker from "@/components/partner/PartnerDatePicker";
import PartnerSelect from "@/components/partner/PartnerSelect";
import {
  formatPartnerDate,
  formatPartnerDateTime,
  formatPartnerDayMonth,
  formatPartnerMonth,
  formatPartnerYear,
} from "@/lib/partner-date";
import "./page.css";

type DatePreset = "today" | "7d" | "30d" | "year" | "custom";
type Granularity = "daily" | "weekly" | "monthly" | "yearly";
type Comparison = "previous-period" | "previous-month" | "previous-year";
type Breakdown = "court" | "period" | "payment";
type Summary = { bookings:number; customers:number; revenue:number; averageBookingValue:number; occupancyRate:number|null };
type SeriesPoint = { bucket:string; bookings:number; revenue:number };
type Court = { id:string; name:string; bookings:number; revenue:number; booked_hours:number; utilization:number|null };
type Customer = { id:string; name:string; bookings:number; revenue:number; preferred_court:string|null };
type RangeData = { summary:Summary; series:SeriesPoint[]; bookingStatuses:{status:string;value:number}[];
  bookingHours:{label:string;sort_order:number;value:number}[]; courts:Court[]; customers:Customer[];
  customerMetrics:{newCustomers:number;returningCustomers:number;repeatCustomers:number} };
type ReportData = { range:{from:string;to:string}; comparisonRange:{from:string;to:string}; granularity:Granularity;
  current:RangeData; comparison:RangeData; capabilities:{occupancy:boolean;occupancyReason:string;
  paymentMethodBreakdown:boolean;paymentMethodReason:string} };
type HistoryItem = { id:string; report_type:string; date_from:string; date_to:string; comparison:Comparison;
  granularity:Granularity; format:"CSV"; snapshot:ReportData; created_at:string };
type HistoryPage = { content:HistoryItem[];page:number;size:number;totalElements:number;totalPages:number;last:boolean };

const API_BASE = process.env.NEXT_PUBLIC_PARTNER_API_URL || "http://localhost:8090/api/v1";
const HISTORY_SIZE = 3;
const COLORS = ["#0C4A38", "#C8F550", "#8AAE75", "#DDE7DF", "#87A99B", "#E7C96A"];

function dateInput(date:Date){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,10)}
function presetDates(preset:Exclude<DatePreset,"custom">){const end=new Date();const start=new Date(end);
  if(preset==="7d")start.setDate(end.getDate()-6); else if(preset==="30d")start.setDate(end.getDate()-29);
  else if(preset==="year"){start.setMonth(0,1);}
  return {from:dateInput(start),to:dateInput(end)};}
function shiftYear(date:Date){const day=date.getDate();date.setFullYear(date.getFullYear()-1);if(date.getDate()!==day)date.setDate(0);return date}
function comparisonDates(from:string,to:string,comparison:Comparison){const start=new Date(`${from}T12:00:00`);const end=new Date(`${to}T12:00:00`);
  if(comparison==="previous-month"){return {from:dateInput(new Date(start.getFullYear(),start.getMonth()-1,1,12)),to:dateInput(new Date(start.getFullYear(),start.getMonth(),0,12))};}
  if(comparison==="previous-year")return {from:dateInput(shiftYear(new Date(start))),to:dateInput(shiftYear(new Date(end)))};
  const days=Math.round((end.getTime()-start.getTime())/86400000)+1;const previousEnd=new Date(start);previousEnd.setDate(start.getDate()-1);
  const previousStart=new Date(previousEnd);previousStart.setDate(previousEnd.getDate()-days+1);return {from:dateInput(previousStart),to:dateInput(previousEnd)};}
function currency(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value)}
function compactCurrency(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",notation:"compact",maximumFractionDigits:2}).format(value)}
function growth(current:number,previous:number){if(previous===0)return current===0?0:null;return ((current-previous)/previous)*100}
function percent(value:number,total:number){return total?value/total*100:0}
function escapeCsv(value:string|number){return `"${String(value).replaceAll('"','""')}"`}
function labelBucket(value:string,granularity:Granularity){return granularity==="yearly"?formatPartnerYear(value):granularity==="monthly"?formatPartnerMonth(value):formatPartnerDayMonth(value)}
function initials(name:string){return name.split(" ").filter(Boolean).map((part)=>part[0]).join("").slice(0,2).toUpperCase()}
function statusTone(status:string){return status==="REJECTED"?"cancelled":status.toLowerCase()}

async function api<T>(path:string,init?:RequestInit):Promise<T>{const token=await getCurrentAccessToken();const response=await fetch(`${API_BASE}${path}`,{
  ...init,headers:{Authorization:`Bearer ${token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});
  const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error?.message||"Unable to load reports.");return result.data;}

function KpiCard({label,value,detail,trend,icon:Icon}:{label:string;value:string;detail:string;trend:number|null;icon:LucideIcon}){
  const positive=(trend??0)>=0;return <article className="stat-card"><div className="stat-card-header"><span>{label}</span><span className="stat-icon"><Icon size={20}/></span></div>
    <h2>{value}</h2><div className="stat-comparison">{trend===null?<span>New</span>:<span className={positive?"positive":"negative"}>{positive?<ArrowUp size={12}/>:<ArrowDown size={12}/>} {Math.abs(trend).toFixed(1)}%</span>}<p>{detail}</p></div></article>}
function ReportsSkeleton(){return <div className="reports-loading" aria-label="Loading reports"><div className="loading-kpis">{Array.from({length:4}).map((_,i)=><span key={i}/>)}</div><div className="loading-panels"><span/><span/></div></div>}

export default function ReportsPage(){
  const defaults=presetDates("30d");
  const [datePreset,setDatePreset]=useState<DatePreset>("30d");const [startDate,setStartDate]=useState(defaults.from);const [endDate,setEndDate]=useState(defaults.to);
  const [appliedRange,setAppliedRange]=useState(defaults);const comparison:Comparison="previous-period";
  const [granularity,setGranularity]=useState<Granularity>("monthly");const [breakdown,setBreakdown]=useState<Breakdown>("court");
  const [data,setData]=useState<ReportData|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  const [showExportPanel,setShowExportPanel]=useState(false);const [historyPage,setHistoryPage]=useState(0);const [history,setHistory]=useState<HistoryPage|null>(null);

  useEffect(()=>{if(datePreset!=="custom"||!startDate||!endDate||startDate>endDate)return;const timer=setTimeout(()=>setAppliedRange({from:startDate,to:endDate}),400);return()=>clearTimeout(timer)},[datePreset,startDate,endDate]);
  const loadReport=useCallback(async(signal?:AbortSignal)=>{if(appliedRange.from>appliedRange.to)return;setLoading(true);setError("");try{const compare=comparisonDates(appliedRange.from,appliedRange.to,comparison);
    const params=new URLSearchParams({from:appliedRange.from,to:appliedRange.to,compareFrom:compare.from,compareTo:compare.to,granularity});
    setData(await api<ReportData>(`/reports/summary?${params}`,{signal}));}catch(err){if((err as Error).name!=="AbortError")setError(err instanceof Error?err.message:"Unable to load reports.")}finally{if(!signal?.aborted)setLoading(false)}},[appliedRange,comparison,granularity]);
  const loadHistory=useCallback(async()=>{try{setHistory(await api<HistoryPage>(`/reports/history?page=${historyPage}&size=${HISTORY_SIZE}`))}catch{/* Main report error handling remains independent. */}},[historyPage]);
  useEffect(()=>{const controller=new AbortController();loadReport(controller.signal);return()=>controller.abort()},[loadReport]);useEffect(()=>{loadHistory()},[loadHistory]);

  function applyPreset(value:Exclude<DatePreset,"custom">){const range=presetDates(value);setDatePreset(value);setStartDate(range.from);setEndDate(range.to);setAppliedRange(range)}
  const current=data?.current;const previous=data?.comparison;const totalBookings=current?.summary.bookings??0;
  const revenueGrowth=data?growth(current!.summary.revenue,previous!.summary.revenue):0;const bookingGrowth=data?growth(totalBookings,previous!.summary.bookings):0;
  const customerGrowth=data?growth(current!.summary.customers,previous!.summary.customers):0;
  const repeatRate=current?percent(current.customerMetrics.repeatCustomers,current.summary.customers):0;
  const peakHour=current?.bookingHours.reduce((best,item)=>item.value>best.value?item:best,current.bookingHours[0]??{label:"Not enough data",value:0,sort_order:0});
  const bestCourt=current?.courts.find((court)=>court.revenue>0);const maxSeries=Math.max(1,...(current?.series.map((p)=>p.revenue)??[]),...(previous?.series.map((p)=>p.revenue)??[]));
  const chartPoints=(current?.series??[]).map((point,index)=>({point,previous:previous?.series[index],height:Math.max(3,point.revenue/maxSeries*170),previousHeight:Math.max(3,(previous?.series[index]?.revenue??0)/maxSeries*170)}));
  const statusTotal=current?.bookingStatuses.reduce((sum,item)=>sum+item.value,0)??0;
  const hourMax=Math.max(1,...(current?.bookingHours.map((item)=>item.value)??[]));
  const breakdownItems=useMemo(()=>{if(!current)return[];if(breakdown==="court")return current.courts.filter(c=>c.revenue>0).map((c,i)=>({label:c.name,value:c.revenue,color:COLORS[i%COLORS.length]}));
    if(breakdown==="period")return current.series.filter(p=>p.revenue>0).map((p,i)=>({label:labelBucket(p.bucket,granularity),value:p.revenue,color:COLORS[i%COLORS.length]}));return[]},[current,breakdown,granularity]);
  const breakdownTotal=breakdownItems.reduce((sum,item)=>sum+item.value,0);const donut=useMemo(()=>{let cursor=0;return `conic-gradient(${breakdownItems.map(item=>{const start=cursor;cursor+=percent(item.value,breakdownTotal);return `${item.color} ${start}% ${cursor}%`}).join(",")||"#DDE7DF 0 100%"})`},[breakdownItems,breakdownTotal]);

  function csvRows(report:ReportData){return [["Pickelton Partner Report"],["Date From",formatPartnerDate(report.range.from)],["Date To",formatPartnerDate(report.range.to)],["Comparison From",formatPartnerDate(report.comparisonRange.from)],["Comparison To",formatPartnerDate(report.comparisonRange.to)],["Granularity",report.granularity],[],
    ["Metric","Current","Comparison"],["Total Revenue",report.current.summary.revenue,report.comparison.summary.revenue],["Total Bookings",report.current.summary.bookings,report.comparison.summary.bookings],["Unique Customers",report.current.summary.customers,report.comparison.summary.customers],["Average Booking Value",report.current.summary.averageBookingValue,report.comparison.summary.averageBookingValue],[],
    ["Revenue Period","Revenue","Bookings"],...report.current.series.map(p=>[labelBucket(p.bucket,report.granularity),p.revenue,p.bookings]),[],["Court","Revenue","Bookings","Booked Hours"],...report.current.courts.map(c=>[c.name,c.revenue,c.bookings,c.booked_hours]),[],["Customer","Revenue","Bookings","Preferred Court"],...report.current.customers.map(c=>[c.name,c.revenue,c.bookings,c.preferred_court??""])];}
  function downloadCsv(filename:string,report:ReportData){const csv=csvRows(report).map(row=>row.map(escapeCsv).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.click();URL.revokeObjectURL(url)}
  async function exportCurrent(){if(!data)return;downloadCsv("pickelton-business-report.csv",data);setShowExportPanel(false);try{await api("/reports/history",{method:"POST",body:JSON.stringify({reportType:"Business Summary",dateFrom:data.range.from,dateTo:data.range.to,comparison,granularity,format:"CSV",snapshot:data})});setHistoryPage(0);await loadHistory()}catch(err){setError(err instanceof Error?`Report downloaded, but history could not be saved: ${err.message}`:"Report history could not be saved.")}}

  if(loading&&!data)return <main className="reports-page"><ReportsSkeleton/></main>;
  if(error&&!data)return <main className="reports-page"><section className="report-card reports-error-state"><h2>Could not load reports</h2><p>{error}</p><button type="button" className="primary-btn" onClick={()=>loadReport()}><RefreshCw size={16}/>Retry</button></section></main>;
  if(!data||!current||!previous)return null;

  return <main className="reports-page">
    <section className="reports-hero"><div className="hero-decoration hero-decoration-large"/><div className="hero-decoration hero-decoration-small"/><div className="hero-main"><div><span className="page-eyebrow">REPORTS</span><h1>Business Performance</h1><p>Monitor revenue, bookings, customers and court performance.</p></div>
      <div className="hero-actions"><label><span>Date From</span><PartnerDatePicker ariaLabel="Date From" value={startDate} max={endDate} onChange={value=>{setDatePreset("custom");setStartDate(value)}}/></label><label><span>Date To</span><PartnerDatePicker ariaLabel="Date To" value={endDate} min={startDate} onChange={value=>{setDatePreset("custom");setEndDate(value)}}/></label>
      <div className="export-control"><button type="button" className="primary-btn" onClick={()=>setShowExportPanel(v=>!v)} aria-expanded={showExportPanel}><Download size={18}/>Export Report</button>{showExportPanel&&<div className="export-panel"><div className="export-panel-header"><div><strong>Export Report</strong><span>{formatPartnerDate(data.range.from)} – {formatPartnerDate(data.range.to)}</span></div><button type="button" onClick={()=>setShowExportPanel(false)} aria-label="Close export panel"><X size={17}/></button></div><button type="button" className="export-option" onClick={exportCurrent}><FileSpreadsheet size={19}/><span><strong>CSV Report</strong><small>Available now</small></span><CheckCircle2 size={16}/></button><button type="button" className="export-option" disabled><FileText size={19}/><span><strong>PDF Report</strong><small>Unavailable</small></span></button><button type="button" className="export-option" disabled><FileSpreadsheet size={19}/><span><strong>Excel Report</strong><small>Unavailable</small></span></button></div>}</div></div></div>
      <div className="hero-bottom"><div className="date-presets">{[["today","Today"],["7d","Last 7 Days"],["30d","Last 30 Days"],["year","This Year"]].map(([value,label])=><button type="button" className={datePreset===value?"active":undefined} onClick={()=>applyPreset(value as Exclude<DatePreset,"custom">)} key={value}>{label}</button>)}</div><div className="hero-kpis"><div><span>Revenue</span><strong>{compactCurrency(current.summary.revenue)}</strong></div><div><span>Growth</span><strong>{revenueGrowth===null?"New":`${revenueGrowth>=0?"+":""}${revenueGrowth.toFixed(1)}%`}</strong></div><div><span>Bookings</span><strong>{totalBookings}</strong></div></div></div></section>
    {error&&<div className="reports-inline-error">{error}<button type="button" onClick={()=>setError("")} aria-label="Dismiss"><X size={14}/></button></div>}
    <section className="stats-grid"><KpiCard label="Total Revenue" value={currency(current.summary.revenue)} detail="versus comparison period" trend={revenueGrowth} icon={IndianRupee}/><KpiCard label="Total Bookings" value={String(totalBookings)} detail="versus comparison period" trend={bookingGrowth} icon={CalendarDays}/><KpiCard label="Unique Customers" value={String(current.summary.customers)} detail="customers who booked" trend={customerGrowth} icon={Users}/><KpiCard label="Average Booking Value" value={currency(current.summary.averageBookingValue)} detail="confirmed/completed bookings" trend={growth(current.summary.averageBookingValue,previous.summary.averageBookingValue)} icon={BarChart3}/></section>
    {totalBookings===0?<section className="report-card reports-empty-state"><span><CalendarDays size={25}/></span><h3>No bookings in this date range</h3><p>Choose another range to view report analytics.</p></section>:<>
    <section className="analytics-grid primary-analytics"><article className="report-card revenue-card"><header className="card-header"><div><span className="page-eyebrow">REVENUE</span><h2>Revenue Analytics</h2><p>Current and comparison-period performance</p></div><div className="granularity-control">{(["daily","weekly","monthly","yearly"] as const).map(value=><button type="button" className={granularity===value?"active":undefined} onClick={()=>setGranularity(value)} key={value}>{value}</button>)}</div></header><div className="revenue-summary"><div><span>Total Revenue</span><strong>{currency(current.summary.revenue)}</strong></div><div><span>Average Booking Value</span><strong>{currency(current.summary.averageBookingValue)}</strong></div><div><span>Growth</span><strong className={revenueGrowth!==null&&revenueGrowth>=0?"positive":"negative"}>{revenueGrowth===null?"New":`${revenueGrowth.toFixed(1)}%`}</strong></div></div><div className="chart-legend"><span><i className="current"/>Current period</span><span><i className="previous"/>Comparison period</span></div><div className="chart" role="img" aria-label={`${granularity} revenue chart`}><div className="chart-grid-lines"><span/><span/><span/><span/></div>{chartPoints.map(({point,previous:prior,height,previousHeight})=><div className="chart-column" key={point.bucket}><div className="chart-bars"><span className="bar previous-bar" style={{height:previousHeight}} title={`Previous: ${currency(prior?.revenue??0)}`}/><span className="bar current-bar" style={{height}} title={`Current: ${currency(point.revenue)}`}/></div><span>{labelBucket(point.bucket,granularity)}</span></div>)}</div></article>
      <article className="report-card booking-analytics"><header className="card-header"><div><span className="page-eyebrow">BOOKINGS</span><h2>Booking Analytics</h2><p>Peak periods and status distribution</p></div></header><div className="booking-highlight"><span className="highlight-icon"><Clock3 size={20}/></span><div><span>Peak Booking Period</span><strong>{peakHour?.label??"Not enough data"}</strong><small>{peakHour?.value??0} bookings</small></div></div><div className="booking-hour-list">{current.bookingHours.map(item=><div key={item.label}><div><span>{item.label}</span><strong>{item.value}</strong></div><div className="progress-track"><span style={{width:`${item.value/hourMax*100}%`}}/></div></div>)}</div><div className="status-distribution"><div className="status-bar">{current.bookingStatuses.map(item=><span className={statusTone(item.status)} style={{width:`${percent(item.value,statusTotal)}%`}} key={item.status}/>)}</div><div className="status-legend">{current.bookingStatuses.map(item=><div key={item.status}><span className={statusTone(item.status)}/><small>{item.status}</small><strong>{percent(item.value,statusTotal).toFixed(0)}%</strong></div>)}</div></div></article></section>
    <section className="analytics-grid"><article className="report-card"><header className="card-header"><div><span className="page-eyebrow">COURTS</span><h2>Court Performance</h2><p>Bookings and revenue contribution</p></div></header><div className="court-performance-list">{current.courts.map((court,index)=>{const prior=previous.courts.find(item=>item.id===court.id);const trend=growth(court.revenue,prior?.revenue??0);return <div className="court-performance-row" key={court.id}><span className="court-rank">{index+1}</span><div className="court-performance-main"><div><strong>{court.name}</strong><span>{court.bookings} bookings · {court.booked_hours.toFixed(1)} booked hours</span></div><div className="progress-track"><span style={{width:`${percent(court.revenue,current.summary.revenue)}%`}}/></div></div><div className="court-performance-value"><strong>{percent(court.revenue,current.summary.revenue).toFixed(0)}%</strong><span>{currency(court.revenue)}</span></div><span className={`trend ${trend!==null&&trend<0?"negative":"positive"}`}>{trend===null?"New":`${trend>=0?"+":""}${trend.toFixed(0)}%`}</span></div>})}</div><p className="metric-note">Utilization unavailable: {data.capabilities.occupancyReason}</p></article>
      <article className="report-card"><header className="card-header"><div><span className="page-eyebrow">CUSTOMERS</span><h2>Customer Insights</h2><p>Actual customers with bookings in this range</p></div></header><div className="customer-metrics"><div><span>New Customers</span><strong>{current.customerMetrics.newCustomers}</strong><small>first-ever booking in range</small></div><div><span>Returning</span><strong>{current.customerMetrics.returningCustomers}</strong><small>booked before this range</small></div><div><span>Repeat Rate</span><strong>{repeatRate.toFixed(0)}%</strong><small>2+ bookings in range</small></div></div><div className="top-customers"><h3>Top Customers</h3>{current.customers.map(customer=><div className="customer-row" key={customer.id}><span className="customer-avatar">{initials(customer.name)}</span><div><strong>{customer.name}</strong><span>{customer.bookings} bookings · {customer.preferred_court??"No court"}</span></div><strong>{currency(customer.revenue)}</strong></div>)}</div></article></section>
    <section className="analytics-grid"><article className="report-card"><header className="card-header"><div><span className="page-eyebrow">BREAKDOWN</span><h2>Revenue Contribution</h2><p>Understand where revenue is generated</p></div><PartnerSelect className="breakdown-selector" value={breakdown} onValueChange={value=>setBreakdown(value as Breakdown)}><option value="court">By Court</option><option value="period">By Period</option><option value="payment" disabled={!data.capabilities.paymentMethodBreakdown}>By Payment Method (Unavailable)</option></PartnerSelect></header><div className="breakdown-content"><div className="donut-chart" style={{background:donut}}><div><strong>{compactCurrency(breakdownTotal)}</strong><span>Total</span></div></div><div className="breakdown-legend">{breakdownItems.map(item=><div key={item.label}><span style={{backgroundColor:item.color}}/><small>{item.label}</small><strong>{percent(item.value,breakdownTotal).toFixed(0)}%</strong></div>)}</div></div><p className="metric-note">{data.capabilities.paymentMethodReason}</p></article>
      <article className="report-card"><header className="card-header"><div><span className="page-eyebrow">INSIGHTS</span><h2>Operational Insights</h2><p>Signals calculated from the selected range</p></div></header><div className="insights-grid"><div className="insight-card"><span className="insight-icon"><IndianRupee size={19}/></span><div><span>Highest-Earning Court</span><strong>{bestCourt?.name??"Not enough data"}</strong><small>{bestCourt?currency(bestCourt.revenue):"No qualifying revenue"}</small></div></div><div className={`insight-card ${revenueGrowth!==null&&revenueGrowth<0?"attention":""}`}><span className="insight-icon">{revenueGrowth!==null&&revenueGrowth<0?<TrendingDown size={19}/>:<TrendingUp size={19}/>}</span><div><span>Revenue Trend</span><strong>{revenueGrowth===null?"New revenue":`${revenueGrowth.toFixed(1)}%`}</strong><small>versus selected comparison</small></div></div><div className="insight-card"><span className="insight-icon"><CalendarDays size={19}/></span><div><span>Peak Booking Period</span><strong>{peakHour?.label??"Not enough data"}</strong><small>{peakHour?.value??0} bookings</small></div></div><div className="insight-card"><span className="insight-icon"><BarChart3 size={19}/></span><div><span>Average Booking Value</span><strong>{currency(current.summary.averageBookingValue)}</strong><small>confirmed/completed bookings</small></div></div></div></article></section></>}
    <section className="report-card report-history"><header className="card-header"><div><span className="page-eyebrow">HISTORY</span><h2>Report History</h2><p>CSV reports generated for this partner</p></div></header>{!history?.content.length?<div className="reports-empty-state"><span><FileText size={25}/></span><h3>No reports generated yet</h3><p>Export your first CSV report to create report history.</p></div>:<><div className="history-table-wrapper"><table className="history-table"><thead><tr><th>Report</th><th>Generated</th><th>Type</th><th>Period</th><th>Status</th><th>Format</th><th className="history-action-heading">Action</th></tr></thead><tbody>{history.content.map(item=><tr key={item.id}><td><span className="report-id">{item.id.slice(0,8).toUpperCase()}</span><strong>Business Performance</strong></td><td>{formatPartnerDateTime(item.created_at)}</td><td>{item.report_type}</td><td>{formatPartnerDate(item.date_from)} – {formatPartnerDate(item.date_to)}</td><td><span className="report-status ready">Ready</span></td><td>{item.format}</td><td className="history-action-cell"><button type="button" className="download-action" onClick={()=>downloadCsv(`report-${item.id.slice(0,8)}.csv`,item.snapshot)}><Download size={14}/>Download</button></td></tr>)}</tbody></table></div><footer className="pagination"><p>Showing {history.page*history.size+1}–{Math.min((history.page+1)*history.size,history.totalElements)} of {history.totalElements}</p><div className="pagination-controls"><button type="button" onClick={()=>setHistoryPage(p=>Math.max(0,p-1))} disabled={history.page===0}><ChevronLeft size={17}/></button>{Array.from({length:history.totalPages}).map((_,i)=><button type="button" className={i===history.page?"active":undefined} onClick={()=>setHistoryPage(i)} key={i}>{i+1}</button>)}<button type="button" onClick={()=>setHistoryPage(p=>Math.min(history.totalPages-1,p+1))} disabled={history.last}><ChevronRight size={17}/></button></div></footer></>}</section>
  </main>;
}
