import { useState } from "react";
import { router } from "expo-router";
import { ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { CardContainer } from "../../components/CardContainer";
import { BackLink } from "../../components/BackLink";
import { BrandMark } from "../../components/BrandMark";
import { InputField } from "../../components/InputField";
import { PrimaryButton } from "../../components/PrimaryButton";
import { apiErrorMessage, createTournament } from "../../services/api";
import type { ThemeColors } from "../../theme/colors";
import { useThemeStyles } from "../../theme/ThemeProvider";
export default function CreateTournamentScreen() { const styles = useThemeStyles(createStyles); const [form, setForm] = useState({ name: "", description: "", clubId: "", entryFee: "0", maxPlayers: "32", startDate: "" }); const [type, setType] = useState<"SINGLES" | "DOUBLES">("SINGLES"); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const field = (name: keyof typeof form) => ({ value: form[name], onChangeText: (value: string) => setForm((current) => ({ ...current, [name]: value })) }); async function submit() { try { setError(""); const event = await createTournament({ ...form, clubId: form.clubId || undefined, entryFee: Number(form.entryFee), maxPlayers: Number(form.maxPlayers), startDate: form.startDate, sportType: "PICKLEBALL", tournamentType: type }); setMessage("Tournament created. The bracket has a new home."); setTimeout(() => router.replace({ pathname: "/tournaments/[id]", params: { id: event.id } }), 500); } catch (cause) { setError(apiErrorMessage(cause)); } } return <View style={styles.wrapper}><SafeAreaView><ScrollView contentContainerStyle={styles.content}><BackLink /><BrandMark compact /><Text style={styles.title}>CREATE{"\n"}<Text style={styles.primary}>TOURNAMENT</Text></Text><Text style={styles.copy}>Set the field, entry, and starting whistle. Host approval is checked by the backend.</Text><CardContainer style={styles.form}><InputField label="EVENT NAME" placeholder="Bengaluru Summer Smash" {...field("name")} /><InputField label="DESCRIPTION" placeholder="Describe the competition" multiline {...field("description")} /><InputField label="CLUB ID (OPTIONAL)" placeholder="Club UUID" autoCapitalize="none" {...field("clubId")} /><InputField label="ENTRY FEE" placeholder="499" keyboardType="number-pad" {...field("entryFee")} /><InputField label="MAX PLAYERS" placeholder="32" keyboardType="number-pad" {...field("maxPlayers")} /><InputField label="START DATE AND TIME" placeholder="2026-06-20T09:00:00" {...field("startDate")} /></CardContainer><View style={styles.types}>{(["SINGLES", "DOUBLES"] as const).map((item) => <PrimaryButton key={item} label={item} variant={type === item ? "primary" : "outline"} onPress={() => setType(item)} style={styles.type} />)}</View>{error ? <Text style={styles.error}>{error}</Text> : null}{message ? <Text style={styles.success}>{message}</Text> : null}<PrimaryButton icon="rocket-outline" label="PUBLISH TOURNAMENT" onPress={submit} /></ScrollView></SafeAreaView></View>; }
const createStyles = (colors: ThemeColors) => ({ wrapper: { backgroundColor: colors.background, flex: 1 }, content: { padding: 18, paddingBottom: 28 }, title: { color: colors.text, fontSize: 35, fontStyle: "italic", fontWeight: "900", lineHeight: 35, marginTop: 18 }, primary: { color: colors.primary }, copy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8 }, form: { borderTopColor: colors.primary, borderTopWidth: 3, marginTop: 18, paddingBottom: 3 }, types: { flexDirection: "row", gap: 8, marginBottom: 14, marginTop: 14 }, type: { flex: 1 }, error: { color: colors.danger, fontSize: 10, marginBottom: 12 }, success: { color: colors.primary, fontSize: 10, marginBottom: 12 } });
