import { useEffect, useState } from "react";
import { router } from "expo-router";
import { ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { CardContainer } from "../../components/CardContainer";
import { BackLink } from "../../components/BackLink";
import { BrandMark } from "../../components/BrandMark";
import { EmptyState } from "../../components/EmptyState";
import { PrimaryButton } from "../../components/PrimaryButton";
import { SectionHeader } from "../../components/SectionHeader";
import { StatusPill } from "../../components/StatusPill";
import { apiErrorMessage, fetchHostStatus, type HostVerification } from "../../services/api";
import type { ThemeColors } from "../../theme/colors";
import { useThemeStyles } from "../../theme/ThemeProvider";
export default function HostStatusScreen() { const styles = useThemeStyles(createStyles); const [status, setStatus] = useState<HostVerification | null>(null); const [loaded, setLoaded] = useState(false); const [error, setError] = useState(""); useEffect(() => { fetchHostStatus().then(setStatus).catch((cause) => setError(apiErrorMessage(cause))).finally(() => setLoaded(true)); }, []); return <View style={styles.wrapper}><SafeAreaView><ScrollView contentContainerStyle={styles.content}><BackLink /><BrandMark compact /><Text style={styles.title}>HOST{"\n"}<Text style={styles.primary}>STATUS</Text></Text><Text style={styles.copy}>Keep verification progress and tournament tools in one calm corner.</Text><SectionHeader title="APPLICATION" />{error ? <Text style={styles.error}>{error}</Text> : null}{!loaded ? <Text style={styles.copy}>Loading application...</Text> : status ? <CardContainer style={styles.card}><View style={styles.top}><Text style={styles.name}>{status.fullName}</Text><StatusPill label={status.status.replaceAll("_", " ")} tone={status.status === "APPROVED" ? "primary" : "gold"} /></View><Text style={styles.meta}>SUBMITTED {new Date(status.submittedAt).toLocaleDateString("en-IN")}</Text><Text style={styles.copy}>Your identity review controls access to host-only tournament creation.</Text>{status.rejectionReason ? <Text style={styles.error}>{status.rejectionReason}</Text> : null}</CardContainer> : <EmptyState title="NO HOST APPLICATION" copy="Complete identity verification before creating a tournament." />}{status?.status === "APPROVED" ? <PrimaryButton icon="add-circle-outline" label="CREATE TOURNAMENT" onPress={() => router.push("/tournaments/create")} style={styles.button} /> : <PrimaryButton icon="shield-checkmark-outline" label={status ? "UPDATE APPLICATION" : "APPLY TO HOST"} onPress={() => router.push("/host/apply")} style={styles.button} />}</ScrollView></SafeAreaView></View>; }
const createStyles = (colors: ThemeColors) => ({ wrapper: { backgroundColor: colors.background, flex: 1 }, content: { padding: 18 }, title: { color: colors.text, fontSize: 35, fontStyle: "italic", fontWeight: "900", lineHeight: 35, marginTop: 19 }, primary: { color: colors.primary }, copy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8 }, card: { borderTopColor: colors.primary, borderTopWidth: 3, gap: 8 }, top: { alignItems: "center", flexDirection: "row", gap: 8, justifyContent: "space-between" }, name: { color: colors.text, flex: 1, fontSize: 15, fontWeight: "900" }, meta: { color: colors.gold, fontSize: 9, fontWeight: "900" }, error: { color: colors.danger, fontSize: 10, marginTop: 10 }, button: { marginTop: 14 } });
