import { useEffect, useState } from "react";
import { router, useLocalSearchParams } from "expo-router";
import { ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { CardContainer } from "../../../components/CardContainer";
import { EmptyState } from "../../../components/EmptyState";
import { StatusPill } from "../../../components/StatusPill";
import { fetchLeaderboard, type LeaderboardEntry } from "../../../services/api";
import type { ThemeColors } from "../../../theme/colors";
import { useThemeStyles } from "../../../theme/ThemeProvider";
const preview = [{ userId: "1", name: "Meera Shah", email: "", played: 5, won: 5, lost: 0, points: 15 }, { userId: "2", name: "Rohan Mehta", email: "", played: 5, won: 4, lost: 1, points: 12 }, { userId: "3", name: "Ananya Rao", email: "", played: 5, won: 3, lost: 2, points: 9 }];
export default function LeaderboardScreen() { const styles = useThemeStyles(createStyles); const { id } = useLocalSearchParams<{ id: string }>(); const [entries, setEntries] = useState<LeaderboardEntry[]>([]); useEffect(() => { if (id.startsWith("preview-")) setEntries(preview); else fetchLeaderboard(id).then((board) => setEntries(board.entries)).catch(() => setEntries([])); }, [id]); return <View style={styles.wrapper}><SafeAreaView><ScrollView contentContainerStyle={styles.content}><Text onPress={() => router.back()} style={styles.back}>BACK TO EVENT</Text><Text style={styles.brand}>LIVE STANDINGS</Text><Text style={styles.title}>LEADERBOARD</Text><Text style={styles.copy}>Wins do the talking. Points settle the louder conversations.</Text><CardContainer style={styles.table}><View style={styles.row}><Text style={styles.headRank}>#</Text><Text style={styles.headName}>PLAYER</Text><Text style={styles.head}>W</Text><Text style={styles.head}>L</Text><Text style={styles.head}>PTS</Text></View>{entries.map((entry, index) => <View key={entry.userId} style={styles.row}><Text style={styles.rank}>{index + 1}</Text><Text style={styles.name}>{entry.name}</Text><Text style={styles.cell}>{entry.won}</Text><Text style={styles.cell}>{entry.lost}</Text><Text style={styles.points}>{entry.points}</Text></View>)}</CardContainer>{entries.length ? <StatusPill label="UPDATED LIVE" /> : <EmptyState title="NO RESULTS YET" copy="Standings will appear after the first completed match." />}</ScrollView></SafeAreaView></View>; }
const createStyles = (colors: ThemeColors) => ({ wrapper: { backgroundColor: colors.background, flex: 1 }, content: { padding: 18 }, back: { color: colors.muted, fontSize: 10, fontWeight: "900", marginBottom: 20 }, brand: { color: colors.primary, fontSize: 10, fontWeight: "900" }, title: { color: colors.text, fontSize: 35, fontStyle: "italic", fontWeight: "900", marginTop: 16 }, copy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginBottom: 18, marginTop: 8 }, table: { borderTopColor: colors.primary, borderTopWidth: 3, gap: 0, marginBottom: 14, paddingVertical: 4 }, row: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", minHeight: 48 }, headRank: { color: colors.muted, fontSize: 8, fontWeight: "900", width: 24 }, headName: { color: colors.muted, flex: 1, fontSize: 8, fontWeight: "900" }, head: { color: colors.muted, fontSize: 8, fontWeight: "900", textAlign: "center", width: 33 }, rank: { color: colors.gold, fontSize: 13, fontWeight: "900", width: 24 }, name: { color: colors.text, flex: 1, fontSize: 12, fontWeight: "900" }, cell: { color: colors.muted, fontSize: 12, fontWeight: "900", textAlign: "center", width: 33 }, points: { color: colors.primary, fontSize: 13, fontWeight: "900", textAlign: "center", width: 33 } });
